name: Build Typst document
on: push

jobs:
  build-typst-documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: src/main.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: src/main.pdf
